five_sec/models.py
from five_sec import db

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    # 질문 본문
    subject = db.Column(db.String(200), nullable=False)

    # 카테고리: energy / social / action / mood
    category = db.Column(db.String(20), nullable=False)

    # 선택지 텍스트
    left_text = db.Column(db.String(100), nullable=False)
    right_text = db.Column(db.String(100), nullable=False)

    # 선택 시 점수 (해당 카테고리 기준)
    left_score = db.Column(db.Integer, nullable=False)
    right_score = db.Column(db.Integer, nullable=False)

five_sec/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)
    app.config["SECRET_KEY"] = "dev-secret-key"

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    # bp
    from .views import main_views, question_views, static_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(question_views.bp)
    app.register_blueprint(static_views.bp)

    return app

five_sec/views/main_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def hello():
    return render_template('hello.html')

five_sec/views/question_views.py
from flask import Blueprint, render_template, url_for, session
from werkzeug.utils import redirect
from sqlalchemy import func
from five_sec.models import Question
import random

bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/')
def question():
    session["question_ids"] = list()
    while len(session["question_ids"]) < 5:
        temp_num = random.randint(1, 20)
        if temp_num not in session["question_ids"]:
            session["question_ids"].append(temp_num)

    return redirect(url_for('question.start'))

@bp.route('/start')
def start():
    if len(session["question_ids"]) > 0:
        temp_list = session["question_ids"]
        temp_id = temp_list.pop(0)
        session["question_ids"] = temp_list
        return redirect(url_for('question.question_detail', question_id=temp_id))
    else:
        return redirect(url_for('question.end'))

@bp.route('/<int:question_id>')
def question_detail(question_id):
    question_ = Question.query.get_or_404(question_id)
    return render_template('question_detail.html', question_=question_)

@bp.route('/end')
def end():
    return redirect(url_for('main.hello'))

five_sec/views/static_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect

bp = Blueprint('static', __name__, url_prefix='/')


@bp.route('/static')
def static():
    return render_template('static.html')

five_sec/templates/hello.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Simple Test</title>
</head>
<body>
    <h1>Flask URL 테스트</h1>

    <ul>
        <li>
            <a href="{{ url_for('question.question') }}">
                question.question
            </a>
        </li>
        <li>
            <a href="{{ url_for('static.static') }}">
                static.static
            </a>
        </li>
    </ul>

</body>
</html>

five_sec/templates/question.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Hello World</h1>
    <p>여기는 question</p>
</body>
</html>

five_sec/templates/question_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Question</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    >
</head>

<body class="bg-light">

<div class="container py-5" style="max-width: 420px;">

    <div class="card">
        <div class="card-body text-center">

            <h4 class="mb-4">{{ question_.subject }}</h4>

            <div class="d-grid gap-3">
                <button class="btn btn-outline-secondary btn-lg">
                    <a href="{{ url_for('question.start') }}">
                        {{ question_.left_text }}
                    </a>
                </button>


                <button class="btn btn-outline-secondary btn-lg">
                    <a href="{{ url_for('question.start') }}">
                        {{ question_.right_text }}
                    </a>
                </button>
            </div>

        </div>
    </div>



</div>

</body>
</html>

five_sec/templates/static.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Hello World</h1>
    <p>여기는 static</p>
</body>
</html>